### ISSUE TITLE
Macros similar to the old ones "needed".

### ISSUE THREAD

**Issue by mr-phazer** [mr-phazer/QtRenderingWidget#1]
https://github.com/mr-phazer/QtRenderingWidget/blob/fcb04a79c70fae712a0471156929e7248bdf9ff5/Common/Logger.h#L60

Macros from the original are nessecary for full info, function, line, etc, are they only register the function they are called from.
```
#define FULL_FUNC_INFO(message) libtools::string_to_wstring(__func__) +  std::wstring(L": Line: ") + std::to_wstring(__LINE__) + L": " + message

#define LogActionColor(message)  ImplLog::LogActionError(FULL_FUNC_INFO(mssage));
```
Otherwise the client has to to remove to write 
`loggin::logger::LogActionError(FULL_FUNC_INFO("Some error");`
Instead of
`LogActionError(Some error);`

**Comment by Frodo45127** [comment]
This referenced an old branch, so it's not applicable anymore.
